import {
  Package,
  Publish,
  TestTargets,
  Tools,
  builtArtifactFixture,
  defineDeps,
  definePackage,
  dep,
  localFixture,
  npm,
  path,
  peer,
  tool,
  workspace,
} from "tspack/manifest";

/**
 * Generated migration draft for test/unit/package.json.
 * Identity and package.json dependency sections are compatibility-derived facts.
 * MIGRATION_TODO_* comments mark unresolved or manually authored semantics.
 */
const deps = defineDeps({
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  babelCore: tool(npm("@babel/core", "^7.29.7"), { key: "@babel/core" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  babelPluginProposalDecorators: tool(npm("@babel/plugin-proposal-decorators", "^7.29.7"), { key: "@babel/plugin-proposal-decorators" }),
  edgeRuntimeVm: tool(npm("@edge-runtime/vm", "^5.0.0"), { key: "@edge-runtime/vm" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  rolldownPluginBabel: tool(npm("@rolldown/plugin-babel", "^0.2.3"), { key: "@rolldown/plugin-babel" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  standardSchemaSpec: tool(npm("@standard-schema/spec", "^1.1.0"), { key: "@standard-schema/spec" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  testDepEsmNonExisting: tool(path("deps/dep-esm-non-existing"), { key: "@test/dep-esm-non-existing" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  testViteEnvironmentExternal: tool(path("projects/vite-environment-external"), { key: "@test/vite-environment-external" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  testViteExternal: tool(path("projects/vite-external"), { key: "@test/vite-external" }),
  vitestExpect: tool(workspace("@vitest/expect"), { key: "@vitest/expect" }),
  vitestMocker: tool(workspace("@vitest/mocker"), { key: "@vitest/mocker" }),
  vitestPrettyFormat: tool(workspace("@vitest/pretty-format"), { key: "@vitest/pretty-format" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestTestDepCjs: tool(path("deps/dep-cjs"), { key: "@vitest/test-dep-cjs" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestTestDepNestedCjs: tool(path("deps/dep-nested-cjs"), { key: "@vitest/test-dep-nested-cjs" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestTestDep1: tool(path("deps/dep1"), { key: "@vitest/test-dep1" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestTestDep2: tool(path("deps/dep2"), { key: "@vitest/test-dep2" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestTestFn: tool(path("deps/dep-fn"), { key: "@vitest/test-fn" }),
  vitestUtils: tool(workspace("@vitest/utils"), { key: "@vitest/utils" }),
  vitestWebWorker: tool(workspace("@vitest/web-worker"), { key: "@vitest/web-worker" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vueuseIntegrations: tool(npm("@vueuse/integrations", "^14.4.0"), { key: "@vueuse/integrations" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  happyDom: tool(npm("happy-dom", "^20.11.6"), { key: "happy-dom" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  httpClient: tool(path("projects/http-client"), { key: "http-client" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  immutable: tool(npm("immutable", "5.1.9")),
  // Required only by the jsdom-environment fixture target family.
  jsdom: tool(npm("jsdom", "^29.1.1")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  loupe: tool(npm("loupe", "^3.2.1")),
  magicString: tool(npm("magic-string", "^1.2.2"), { key: "magic-string" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  memfs: tool(npm("memfs", "^4.68.1")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  obug: tool(npm("obug", "^2.1.4")),
  pathe: tool(npm("pathe", "^2.0.3")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  react: tool(npm("react", "^19.2.8")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  react18: tool(npm("react", "18.3.1"), { key: "react-18" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  sinon: tool(npm("sinon", "^22.1.0")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  sinonChai: tool(npm("sinon-chai", "^4.0.1"), { key: "sinon-chai" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  temporalPolyfill: tool(npm("temporal-polyfill", "~0.3.2"), { key: "temporal-polyfill" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  tinyrainbow: tool(npm("tinyrainbow", "^3.1.1")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  tinyspy: tool(npm("tinyspy", "^4.0.4")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  url: tool(npm("url", "^0.11.4")),
  vite: tool(npm("vite", "8.0.11")),
  // The bounded CI targets need an executable harness from a clean checkout.
  // The workspace package has source only until the broader Vitest build runs.
  vitest: tool(npm("vitest", "5.0.0-rc.3")),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestEnvironmentCustom: tool(path("vitest-environment-custom"), { key: "vitest-environment-custom" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vitestPackageExports: tool(npm("vitest-package-exports", "^1.2.0"), { key: "vitest-package-exports" }),
  // MIGRATION_TODO_DEP_CLASSIFICATION: mechanically classified from devDependencies.
  vue: tool(npm("vue", "^3.5.41")),
});

export default definePackage(
  <Package
    name="@vitest/test-unit"
    version="0.0.0"
    kind="app"
    dependencies={{
      values: [
        deps.babelCore,
        deps.babelPluginProposalDecorators,
        deps.edgeRuntimeVm,
        deps.rolldownPluginBabel,
        deps.standardSchemaSpec,
        deps.testDepEsmNonExisting,
        deps.testViteEnvironmentExternal,
        deps.testViteExternal,
        deps.vitestExpect,
        deps.vitestMocker,
        deps.vitestPrettyFormat,
        deps.vitestTestDepCjs,
        deps.vitestTestDepNestedCjs,
        deps.vitestTestDep1,
        deps.vitestTestDep2,
        deps.vitestTestFn,
        deps.vitestUtils,
        deps.vitestWebWorker,
        deps.vueuseIntegrations,
        deps.httpClient,
        deps.happyDom,
        deps.immutable,
        deps.jsdom,
        deps.loupe,
        deps.magicString,
        deps.memfs,
        deps.obug,
        deps.pathe,
        deps.react,
        deps.react18,
        deps.sinon,
        deps.sinonChai,
        deps.temporalPolyfill,
        deps.tinyrainbow,
        deps.tinyspy,
        deps.url,
        deps.vite,
        deps.vitest,
        deps.vitestEnvironmentCustom,
        deps.vitestPackageExports,
        deps.vue,
      ],
    }}
  >
    <Tools
      values={[
        deps.babelCore,
        deps.babelPluginProposalDecorators,
        deps.rolldownPluginBabel,
      ]}
    />
    <TestTargets
      rows={[
        {
          name: "basic-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: ["test/basic.test.ts"],
          project: "threads",
        },
        {
          name: "snapshot-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/snapshot.test.ts",
            "test/snapshot-custom-serializer.test.ts",
          ],
          project: "threads",
        },
        {
          name: "requirements-fixtures-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/chai-style-assertions-sinon.test.ts",
            "test/interop.test.ts",
          ],
          project: "threads",
          requirements: [
            deps.sinon,
            deps.sinonChai,
            deps.vitestTestDepCjs,
          ],
          fixtures: [
            localFixture(deps.vitestTestDepCjs, {
              name: "dep-cjs",
              binding: "@vitest/test-dep-cjs",
            }),
          ],
        },
        {
          name: "fixture-package-family-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/chai-style-assertions-sinon.test.ts",
            "test/dual-package-hazard.test.ts",
            "test/exports.test.ts",
            "test/immutable.test.ts",
            "test/interop.test.ts",
            "test/mock-fs.test.ts",
            "test/module.test.ts",
            "test/snapshot-react.test.jsx",
            "test/mocking/autospying.test.ts",
            "test/mocking/external.test.ts",
            "test/mocking/factory.test.ts",
            "test/mocking/http-client-mocked.test.ts",
            "test/mocking/http-client-not-mocked.test.ts",
            "test/mocking/nested-default.spec.ts",
            "test/mocking/self-importing.test.ts",
            "test/mocking/tinyspy.test.ts",
          ],
          project: "threads",
          requirements: [
            deps.httpClient,
            deps.immutable,
            deps.jsdom,
            deps.memfs,
            deps.react,
            deps.sinon,
            deps.sinonChai,
            deps.testViteEnvironmentExternal,
            deps.testViteExternal,
            deps.tinyspy,
            deps.vitestPackageExports,
            deps.vitestTestDep1,
            deps.vitestTestDep2,
            deps.vitestTestDepCjs,
            deps.vitestTestDepNestedCjs,
            deps.vitestTestFn,
          ],
          fixtures: [
            localFixture(deps.httpClient, { name: "http-client", binding: "http-client" }),
            localFixture(deps.testViteEnvironmentExternal, {
              name: "vite-environment-external",
              binding: "@test/vite-environment-external",
              mode: "source",
            }),
            localFixture(deps.testViteExternal, {
              name: "vite-external",
              binding: "@test/vite-external",
              mode: "source",
            }),
            localFixture(deps.vitestTestDep1, { name: "dep1", binding: "@vitest/test-dep1" }),
            localFixture(deps.vitestTestDep2, { name: "dep2", binding: "@vitest/test-dep2" }),
            localFixture(deps.vitestTestDepCjs, { name: "dep-cjs", binding: "@vitest/test-dep-cjs" }),
            localFixture(deps.vitestTestDepNestedCjs, { name: "dep-nested-cjs", binding: "@vitest/test-dep-nested-cjs" }),
            localFixture(deps.vitestTestFn, { name: "dep-fn", binding: "@vitest/test-fn" }),
          ],
        },
        {
          name: "react18-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: ["test/snapshot-react-18.test.jsx"],
          project: "threads",
          requirements: [deps.react18],
        },
        {
          name: "additional-package-fixtures-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/imports.test.ts",
            "test/node-protocol-jsdom.spec.ts",
          ],
          project: "threads",
          requirements: [
            deps.jsdom,
            deps.testDepEsmNonExisting,
            deps.url,
          ],
          fixtures: [
            localFixture(deps.testDepEsmNonExisting, {
              name: "dep-esm-non-existing",
              binding: "@test/dep-esm-non-existing",
            }),
          ],
        },
        {
          name: "web-worker-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/web-worker-jsdom.test.ts",
            "test/web-worker-mock.test.ts",
            "test/web-worker-node.test.ts",
          ],
          project: "threads",
          dependsOn: ["@vitest/web-worker:package"],
          builtFixtures: [
            builtArtifactFixture("@vitest/web-worker:package", {
              name: "web-worker-runtime",
              artifact: "runtime",
              binding: "@vitest/web-worker",
            }),
          ],
        },
        {
          name: "expect-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: ["test/expect.test.ts"],
          project: "threads",
          requirements: [
            deps.standardSchemaSpec,
            deps.temporalPolyfill,
          ],
          dependsOn: [
            "@vitest/pretty-format:package",
            "@vitest/utils:package",
          ],
          builtFixtures: [
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifact: "runtime",
              binding: "@vitest/utils",
            }),
          ],
        },
        {
          name: "pretty-format-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: ["test/pretty-format.test.ts"],
          project: "threads",
          requirements: [deps.loupe],
          dependsOn: [
            "@vitest/pretty-format:package",
            "@vitest/utils:package",
          ],
          builtFixtures: [
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifact: "runtime",
              binding: "@vitest/utils",
            }),
          ],
        },
        {
          name: "node-runtime-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/browser-sessions.test.ts",
            "test/doctor-candidates.test.ts",
            "test/duration-breakdown.test.ts",
            "test/environment-diagnostics.test.ts",
            "test/external-module-directory.test.ts",
            "test/file-path.test.ts",
            "test/import-diagnostics.test.ts",
            "test/lookup-package-scope-type.test.ts",
            "test/parse-cjs-conditions.test.ts",
            "test/resolve-file-url.test.ts",
            "test/sequencers.test.ts",
          ],
          project: "threads",
          dependsOn: ["vitest:package"],
          builtFixtures: [
            builtArtifactFixture("@vitest/expect:package", {
              name: "expect-runtime",
              artifact: "javaScript",
              binding: "@vitest/expect",
            }),
            builtArtifactFixture("@vitest/mocker:package", {
              name: "mocker-runtime",
              artifact: "runtime",
              binding: "@vitest/mocker",
            }),
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/snapshot:package", {
              name: "snapshot-runtime",
              artifacts: [
                "environment-js",
                "index-js",
                "manager-js",
                "runtime-chunk",
              ],
              binding: "@vitest/snapshot",
            }),
            builtArtifactFixture("@vitest/spy:package", {
              name: "spy-runtime",
              artifact: "runtime",
              binding: "@vitest/spy",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifacts: ["runtime", "runtime-source-map"],
              binding: "@vitest/utils",
            }),
            builtArtifactFixture("vitest:package", {
              name: "vitest-runtime",
              artifacts: [
                "commonjs",
                "runtime",
                "runtime-chunks",
                "runtime-workers",
                "suppress-warnings",
              ],
              binding: "vitest",
            }),
          ],
        },
        {
          name: "cli-module-diagnostic-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/cli-test.test.ts",
            "test/module-diagnostic.test.ts",
          ],
          project: "threads",
          dependsOn: ["vitest:package"],
          builtFixtures: [
            builtArtifactFixture("@vitest/expect:package", {
              name: "expect-runtime",
              artifact: "javaScript",
              binding: "@vitest/expect",
            }),
            builtArtifactFixture("@vitest/mocker:package", {
              name: "mocker-runtime",
              artifact: "runtime",
              binding: "@vitest/mocker",
            }),
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/snapshot:package", {
              name: "snapshot-runtime",
              artifacts: [
                "environment-js",
                "index-js",
                "manager-js",
                "runtime-chunk",
              ],
              binding: "@vitest/snapshot",
            }),
            builtArtifactFixture("@vitest/spy:package", {
              name: "spy-runtime",
              artifact: "runtime",
              binding: "@vitest/spy",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifacts: ["runtime", "runtime-source-map"],
              binding: "@vitest/utils",
            }),
            builtArtifactFixture("vitest:package", {
              name: "vitest-runtime",
              artifacts: [
                "commonjs",
                "runtime",
                "runtime-chunks",
                "runtime-workers",
                "suppress-warnings",
              ],
              binding: "vitest",
            }),
          ],
        },
        {
          name: "ordinary-core-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/alias.test.ts",
            "test/builtin.test.ts",
            "test/chai-style-assertions.test.ts",
            "test/chainable.test.ts",
            "test/circular.test.ts",
            "test/concurrent-suite.test.ts",
            "test/concurrent.spec.ts",
            "test/custom.test.ts",
            "test/date-mock.test.ts",
            "test/diff.test.ts",
            "test/each.test.ts",
            "test/edge.test.ts",
            "test/error.test.ts",
            "test/esnext-decorator.test.ts",
            "test/esnext.test.ts",
            "test/execution-order.test.ts",
            "test/expect-circular.test.ts",
            "test/expect-poll.test.ts",
            "test/fixture-comments-between-destructure.test.ts",
            "test/fixture-concurrent-beforeEach.test.ts",
            "test/fixture-concurrent.test.ts",
            "test/fixture-initialization.test.ts",
            "test/fixture-options.test.ts",
            "test/fn.test.ts",
            "test/handled-unhandled.test.ts",
            "test/hooks-list.test.ts",
            "test/hooks-parallel.test.ts",
            "test/hooks-stack.test.ts",
            "test/hooks.test.ts",
            "test/isolate.test.ts",
            "test/jest-expect-no-url.test.ts",
            "test/jest-expect.test.ts",
            "test/jest-matcher-utils.test.ts",
            "test/jest-mock.test.ts",
            "test/local-context.test.ts",
            "test/lot-of-tests.test.ts",
            "test/math.test.ts",
            "test/named-overwrite-all.test.ts",
            "test/nested-only.test.ts",
            "test/nested-suite.test.ts",
            "test/nested-test.test.ts",
            "test/on-failed.test.ts",
            "test/on-finished.test.ts",
            "test/only.test.ts",
            "test/pattern.test.ts",
            "test/propagate-options-nested-suite.test.ts",
            "test/random.test.ts",
            "test/repeats.test.ts",
            "test/replace-matcher.test.ts",
            "test/retry-condition.test.ts",
            "test/retry-delay.test.ts",
            "test/retry-only.test.ts",
            "test/retry.test.ts",
            "test/run-if.test.ts",
            "test/self.test.ts",
            "test/sequential.test.ts",
            "test/serialize.test.ts",
            "test/skip-reset-state.test.ts",
            "test/skip.test.ts",
            "test/spy.test.ts",
            "test/stubbed-process.test.ts",
            "test/stubs.test.ts",
            "test/suite.test.tsx",
            "test/task-collector.test.ts",
            "test/task-names.test.ts",
            "test/test-extend-with-top-level-hooks.test.ts",
            "test/test-extend.test.ts",
            "test/test-for-suite.test.ts",
            "test/test-for.test.ts",
            "test/test-name-pattern.test.ts",
            "test/test-options.test.ts",
            "test/test-tags-filter.test.ts",
            "test/threads-specific.threads.test.ts",
            "test/timeout.spec.ts",
            "test/unhandled-skip.test.ts",
            "test/utils-display.spec.ts",
            "test/vi.spec.ts",
            "test/wait.test.ts",
          ],
          project: "threads",
          requirements: [
            deps.edgeRuntimeVm,
            deps.happyDom,
          ],
          dependsOn: [
            "@vitest/expect:package",
            "@vitest/pretty-format:package",
            "@vitest/spy:package",
            "@vitest/utils:package",
          ],
          builtFixtures: [
            builtArtifactFixture("@vitest/expect:package", {
              name: "expect-runtime",
              artifact: "javaScript",
              binding: "@vitest/expect",
            }),
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/spy:package", {
              name: "spy-runtime",
              artifact: "runtime",
              binding: "@vitest/spy",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifacts: ["runtime", "runtime-source-map"],
              binding: "@vitest/utils",
            }),
          ],
        },
        {
          name: "remaining-runtime-built-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "test/browserAutomocker.test.ts",
            "test/child-specific.child_process.test.ts",
            "test/define-ssr.test.ts",
            "test/define-web.test.ts",
            "test/do-mock-reset-modules.test.ts",
            "test/do-mock.test.ts",
            "test/dom-single-line-options.test.ts",
            "test/dom.test.ts",
            "test/dynamic-import.test.ts",
            "test/env-glob.test.ts",
            "test/env-jsdom.test.ts",
            "test/env-runtime.test.ts",
            "test/env.test.ts",
            "test/environments/custom-env.test.ts",
            "test/environments/happy-dom.spec.ts",
            "test/environments/jsdom-options.test.ts",
            "test/environments/jsdom.spec.ts",
            "test/environments/node.spec.ts",
            "test/fs.test.ts",
            "test/happy-dom-custom.test.ts",
            "test/happy-dom.test.ts",
            "test/hoist-import.test.ts",
            "test/hoisted-async-simple.test.ts",
            "test/hoisted-simple.test.ts",
            "test/hooks.test.js",
            "test/import-client.test.ts",
            "test/import-meta-resolve.test.ts",
            "test/injector-esm.test.ts",
            "test/injector-mock.test.ts",
            "test/inline-snap.test.ts",
            "test/inlined.test.ts",
            "test/memory-limit.test.ts",
            "test/mock-internals.test.ts",
            "test/mocked-circular.test.ts",
            "test/mocked-class-restore-all.test.ts",
            "test/mocked-class-restore-explicit.test.ts",
            "test/mocked-class.test.ts",
            "test/mocked-import-circular.test.ts",
            "test/mocked-no-mocks-same.test.ts",
            "test/mocked-no-mocks.test.ts",
            "test/mocked-node-module.test.ts",
            "test/mocked-public-key.test.ts",
            "test/mocked.test.js",
            "test/mocked.test.ts",
            "test/mocking/already-hoisted.test.ts",
            "test/mocking/automocking-class-inheritance.test.ts",
            "test/mocking/automocking.spec.ts",
            "test/mocking/circular-mocks.spec.ts",
            "test/mocking/custom-module-directory.spec.ts",
            "test/mocking/cyclic-import-actual.spec.ts",
            "test/mocking/cyclic-import-original.spec.ts",
            "test/mocking/destructured.test.ts",
            "test/mocking/error-mock.spec.ts",
            "test/mocking/has-extension.spec.ts",
            "test/mocking/hoisted.test.ts",
            "test/mocking/import-actual-query.test.ts",
            "test/mocking/integration.test.ts",
            "test/mocking/retry-dynamic-import.test.ts",
            "test/mocking/spaced.spec.ts",
            "test/mocking/vi-fn.test.ts",
            "test/mocking/vi-mockObject.test.ts",
            "test/mocking/vi-spyOn.test.ts",
            "test/mocking/vi-when.test.ts",
            "test/mocking/virtual.test.ts",
            "test/modes.test.ts",
            "test/moved-snapshot.test.ts",
            "test/node-protocol-node.spec.ts",
            "test/require.test.ts",
            "test/resolve-ssr.test.ts",
            "test/resolve-web.test.ts",
            "test/rpc.spec.ts",
            "test/snapshot-async.test.ts",
            "test/snapshot-concurrent-sync.test.ts",
            "test/snapshot-concurrent.test.ts",
            "test/snapshot-file.test.ts",
            "test/snapshot-inline-(parentheses).test.ts",
            "test/snapshot-inline.test.ts",
            "test/sourcemap.test.ts",
            "test/strict.test.js",
            "test/tab-effect.spec.mjs",
            "test/timers-getMockedSystemTime.test.ts",
            "test/timers-jsdom.test.ts",
            "test/timers-node.test.ts",
            "test/timers-queueMicrotask.test.ts",
            "test/timers-temporal.test.ts",
            "test/unmock-import.test.ts",
            "test/url-ssr.test.ts",
            "test/url-web.test.ts",
            "test/utils.spec.ts",
            "test/vm-code-cache.test.ts",
            "test/wasm.test.ts",
            "test/write-file-dynamic-import.test.ts",
          ],
          project: "threads",
          requirements: [
            deps.happyDom,
            deps.jsdom,
            deps.magicString,
            deps.pathe,
            deps.temporalPolyfill,
            deps.url,
            deps.vite,
            deps.vitestEnvironmentCustom,
          ],
          fixtures: [
            localFixture(deps.vitestEnvironmentCustom, {
              name: "vitest-environment-custom",
              binding: "vitest-environment-custom",
            }),
          ],
          dependsOn: [
            "@vitest/mocker:package",
            "@vitest/pretty-format:package",
            "@vitest/spy:package",
          ],
          builtFixtures: [
            builtArtifactFixture("@vitest/mocker:package", {
              name: "mocker-runtime",
              artifact: "runtime",
              binding: "@vitest/mocker",
            }),
            builtArtifactFixture("@vitest/pretty-format:package", {
              name: "pretty-format-runtime",
              artifact: "runtime",
              binding: "@vitest/pretty-format",
            }),
            builtArtifactFixture("@vitest/spy:package", {
              name: "spy-runtime",
              artifact: "runtime",
              binding: "@vitest/spy",
            }),
            builtArtifactFixture("@vitest/utils:package", {
              name: "utils-runtime",
              artifacts: ["runtime", "runtime-source-map"],
              binding: "@vitest/utils",
            }),
          ],
        },
        {
          name: "unit-typecheck-in-source-threads",
          harness: "vitest",
          config: "vite.config.ts",
          sources: [
            "src/in-source/add.ts",
            "src/in-source/fibonacci.ts",
            "test/expect.test-d.ts",
            "test/mocking/vi-fn.test-d.ts",
            "test/vi.test-d.ts",
          ],
          project: "threads",
        },
      ]}
    />
  </Package>,
);
